"""create gemstones table

Revision ID: 7819bfd9dd29
Revises: 
Create Date: 2026-08-28 14:41:04.581407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7819bfd9dd29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemstones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('gemstone_type', sa.Enum('DIAMOND', 'RUBY', 'SAPPHIRE', name='gemstone_type'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('carat_weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gemstones')
    # ### end Alembic commands ###
