"""fix users table

Revision ID: 714865f5b46d
Revises: a9d525f5e224
Create Date: 2026-08-27 07:32:39.381045

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "714865f5b46d"
down_revision: str | Sequence[str] | None = "a9d525f5e224"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
