"""Add gemstone image key

Revision ID: 8b32b4b55353
Revises: 36a4a296b993
Create Date: 2026-09-21 21:29:34.526443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b32b4b55353'
down_revision: Union[str, Sequence[str], None] = '36a4a296b993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gemstones', sa.Column('image_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gemstones', 'image_key')
    # ### end Alembic commands ###
